refactor dto to class and add class-validators
alexMercy/nest9-swagger-codegen pull request #3
Opened 2024-08-26 12:45 UTC by alexMercy

2024-08-27 06:47 UTC, pavlumik requested changes

2024-08-27 06:47 UTC, pavlumik commented on src/utils/getEnums.ts
> +      if(typeof value === 'string')
какое возвращаемое значение "по умолчанию"?
выглядит так, что либо `if` в 8 строке не уместен, либо должно что-то должно возвращаться в случае если value не number, boolean и не string,

2024-08-27 06:47 UTC, pavlumik commented on src/templates/dto/dto.template.ts
> +        throw new Error("don't use no ref object props. If you need use object prop, that create component and use him with $ref")
```suggestion
        throw new Error("don't use no ref object props. If you need use object prop, that create component and use it with $ref")
```

2024-08-27 06:47 UTC, pavlumik commented on src/templates/dto/dto.template.ts
> +    if(data.type === 'array') {
есть ли случай, когда функция может вызываться на объекте без свойства type? потенциально небезопасный код...

2024-08-28 07:22 UTC, pavlumik commented on src/templates/dto/dto.template.ts
> +  const filteredComponents: [string, any][] = dtos.map(dto => ([dto, allOfDereference(api.components.schemas[dto])]))
если я правильно понимаю, при вызове `createDtos` из main.ts параметром dtos передается Set. как происходит конверсия из Set в Array?
есть подозрение, что в 141 строке выполнение ломается, - Set в интерфейсе не имеет функции `map`

2024-08-28 08:35 UTC, alexMercy commented on src/templates/dto/dto.template.ts
> +  const filteredComponents: [string, any][] = dtos.map(dto => ([dto, allOfDereference(api.components.schemas[dto])]))
Изменю в review fix main.ts. Там адаптирую set в array

2024-08-28 12:14 UTC, pavlumik approved these changes

2024-08-28 12:15 UTC, merged